package exceptions;

public enum ExceptionCode
{
	INVALID_FORMAT_DATE,
	INVALID_FORMAT_PHONE,
	INVALID_FORMAT_SPECIAL_CHARACTER,
	INVALID_FORMAT_TOO_LONG_NAME,

	CANNOT_EDIT_NUMBER,
	CANNOT_FIND_CUSTOMER,
	CANNOT_FIND_ORDER,

	FILE_LOCKED,

	NO_INFORMATION
}
